### PR TITLE
Changeset test

### PR DESCRIPTION
**Pull request by jeffsee55**

### CODE REVIEW

**Comment by fergiemcdowall** [comment]
Should this PR be merged?

**Comment by kldavis4** [comment]
@fergiemcdowall we have a fork based on #45 - would be great to get that functionality merged so we can avoid forking

**Comment by fergiemcdowall** [comment]
So on a high level- the has to do with the way with the `level` backend is initialized? Are there any other big changes in your fork?

**Comment by fergiemcdowall** [comment]
I think that merging your fork is probably a good idea if I understand the changes that have been made.

**Comment by kldavis4** [comment]
> So on a high level- the has to do with the way with the `level` backend is initialized? Are there any other big changes in your fork?

Yes, the main change is passing in an instance of a level database instead of the level class. The other change I made was to make the default database for node memory-level instead of classic-level. The reason is that classic has some binary dependencies. I moved it to a dev dependency and updated the CREATED-test to conditionally use classic when in node though.

The biggest impact of this change is on the `search-index` library, so in order to update fii on that project, there will need to be another set of changes. If you are ok with proceeding, I can open up a new PR in this repo with just the changes above.

**Comment by fergiemcdowall** [comment]
Yes, if you want to that would be great- I can publish it as a pre-release and try to get search-index working with it

**Comment by kldavis4** [comment]
@fergiemcdowall here's the new PR with our downstream changes removed: https://github.com/fergiemcdowall/fergies-inverted-index/pull/58

Also have a PR to search-index to make it compatible: https://github.com/fergiemcdowall/search-index/pull/612

**Pull request closed without merging**
